# Generated by Django 4.2.7 on 2023-11-21 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device_management', '0003_rename_devicedata_data_customuser_alter_device_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='user',
        ),
        migrations.CreateModel(
            name='DeviceRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('LO', 'Lev Operator'), ('LE', 'Lev Engineer'), ('LM', 'Lev Manager'), ('OW', 'Owner')], max_length=2)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device_management.device')),
            ],
        ),
    ]
