# Generated by Django 4.2.7 on 2023-11-21 22:06

from django.db import migrations
import django.utils.timezone
import timescale.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('device_management', '0005_device_user_delete_devicerole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='timestamp',
            field=timescale.db.models.fields.TimescaleDateTimeField(default=django.utils.timezone.now, interval='1 day'),
        ),
    ]
